/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hype AMD
 */
public class MainFrame extends javax.swing.JFrame {
    private final dao.EventDAO daoEvent;
    private int selectedNo = -1; // Untuk menyimpan nomor ID baris tabel yang diklik user
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        daoEvent = new dao.EventDAO(); // Inisialisasi objek DAO
        this.setLocationRelativeTo(null); // Agar form muncul di tengah layar monitor
        loadTableData();
    }
    private void loadTableData() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"No", "Nama", "Organizer", "Event", "Status Bayar"}, 0
        );
        java.util.List<model.EventModel> list = daoEvent.getAll();
        for (model.EventModel ev : list) {
            model.addRow(new Object[]{ev.getNo(), ev.getNama(), ev.getOrganizer(), ev.getEvent(), ev.getStatusBayar()});
        }
        tblEvent.setModel(model);
    }

    private void clearFields() {
        txtNama.setText("");
        txtOrganizer.setText("");
        txtEvent.setText("");
        cmbStatus.setSelectedIndex(0);
        selectedNo = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtOrganizer = new javax.swing.JTextField();
        txtEvent = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));

        jLabel1.setText("Nama");

        jLabel2.setText("Organizer");

        jLabel3.setText("Event");

        jLabel4.setText("Status");

        jLabel5.setText("Cari");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvent);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCetak)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnTambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnUbah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnHapus))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrganizer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrganizer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCetak))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
String nama = txtNama.getText().trim();
        String organizer = txtOrganizer.getText().trim();
        String event = txtEvent.getText().trim();
        String status = cmbStatus.getSelectedItem().toString();

        // Validasi input: Kolom tidak boleh kosong
        if (nama.isEmpty() || organizer.isEmpty() || event.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom input wajib diisi!", "Validasi Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.EventModel em = new model.EventModel(0, nama, organizer, event, status);
        if (daoEvent.insert(em)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Event Berhasil Ditambahkan!");
            loadTableData(); // Refresh isi tabel
            clearFields();   // Kosongkan form kembali
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
if (selectedNo == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih baris pada tabel terlebih dahulu yang ingin diubah!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nama = txtNama.getText().trim();
        String organizer = txtOrganizer.getText().trim();
        String event = txtEvent.getText().trim();
        String status = cmbStatus.getSelectedItem().toString();

        if (nama.isEmpty() || organizer.isEmpty() || event.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data tidak boleh ada yang kosong!", "Validasi Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        model.EventModel em = new model.EventModel(selectedNo, nama, organizer, event, status);
        if (daoEvent.update(em)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data Event Berhasil Diperbarui!");
            loadTableData();
            clearFields();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
if (selectedNo == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih data pada tabel terlebih dahulu yang ingin dihapus!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            if (daoEvent.delete(selectedNo)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Event Berhasil Dihapus!");
                loadTableData();
                clearFields();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
try {
            java.text.MessageFormat header = new java.text.MessageFormat("LAPORAN DATA MANAGEMENT EVENT ORGANIZER");
            java.text.MessageFormat footer = new java.text.MessageFormat("Halaman {0,number,integer}");
            
            // Mencetak JTable langsung menjadi dokumen fisik cetak / Simpan PDF cetak bawaan OS
            boolean complete = tblEvent.print(javax.swing.JTable.PrintMode.FIT_WIDTH, header, footer);
            if (complete) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cetak dokumen laporan sukses!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (java.awt.print.PrinterException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal Mencetak: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
String keyword = txtCari.getText().trim();
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
            new Object[]{"No", "Nama", "Organizer", "Event", "Status Bayar"}, 0
        );
        java.util.List<model.EventModel> list = daoEvent.search(keyword);
        for (model.EventModel ev : list) {
            model.addRow(new Object[]{ev.getNo(), ev.getNama(), ev.getOrganizer(), ev.getEvent(), ev.getStatusBayar()});
        }
        tblEvent.setModel(model);        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void tblEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventMouseClicked
int row = tblEvent.getSelectedRow();
        if (row != -1) {
            selectedNo = Integer.parseInt(tblEvent.getValueAt(row, 0).toString());
            txtNama.setText(tblEvent.getValueAt(row, 1).toString());
            txtOrganizer.setText(tblEvent.getValueAt(row, 2).toString());
            txtEvent.setText(tblEvent.getValueAt(row, 3).toString());
            cmbStatus.setSelectedItem(tblEvent.getValueAt(row, 4).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblEventMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEvent;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtOrganizer;
    // End of variables declaration//GEN-END:variables
}
